### ISSUE TITLE
Preview the setup of a Linux machine with Vagrant

### ISSUE THREAD

**Issue by andreoliwa** [sloria/dotfiles#9]
Hi @sloria,

Would you be interested in adding Vagrant to your dotfiles?

Here's my use case.
I currently work on a MacBook, but I also have an Ubuntu laptop.
Sometimes I want to change roles on MacOS, but also test them on Linux while developing.
So I use Vagrant to start a Linux VM and run Ansible there, straight from the MacBook.

I created a branch and [here is a comparison, a preview of what I'm doing](https://github.com/sloria/dotfiles/compare/master...andreoliwa:preview-linux-with-vagrant).

My plan is to use this to check and test this Ansible setup on different Linux distributions, without leaving MacOS.

If you like the idea, I can open a pull request, we continue the discussion and tweak things to fit your repo.

Cheers!

**Comment by sloria** [comment]
Thanks for posting, @andreoliwa . I currently don't need Vagrant/Ubuntu support right now, and I wouldn't be able to put the time in to maintain it properly. Thanks anyway for offering to submit your changes upstream.
